source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target "fourdays" do
  pod "React", :path => "../node_modules/react-native",
               :subspecs => [
                 "Core",
                 "CxxBridge",
                 "DevSupport",
                 "RCTText",
                 "RCTNetwork",
                 "RCTWebSocket",
                 "RCTAnimation",
               ]

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod "DoubleConversion", :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  pod "glog", :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec"
  pod "Folly", :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  pod "RNShare", :path => "../node_modules/react-native-share"
  pod "RNCAsyncStorage", :path => "../node_modules/@react-native-community/async-storage"
  pod "RNGestureHandler", :path => "../node_modules/react-native-gesture-handler"
  pod "RNI18n", :path => "../node_modules/react-native-i18n"
  pod "RNLocalize", :path => "../node_modules/react-native-localize"
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "react-native-google-maps"
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end

    if target.name == "React"
      target.remove_from_project
    end
  end
end
